name: Basic Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    - name: Test and audit
      run: make tidy audit test

    - name: Build
      run: make build

    - name: Check no dirty
      run: make no-dirty
